version: '3.8'
services:
  backend:
    build:
      context: ./todo-backend
    container_name: todo-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/todo_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yourpassword

  frontend:
    build:
      context: ./todo-frontend
    container_name: todo-frontend
    ports:
      - "3000:80"

  mysql:
    image: mysql:8
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
